# Generated by Django 5.2.9 on 2025-12-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='last_seen',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='url',
            name='visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['visited'], name='crawler_url_visited_34ba25_idx'),
        ),
    ]
