# Generated by Django 5.2.9 on 2026-01-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_rename_last_seen_url_created_at_url_visited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
